[package]
name = "datathinking-report"
version = "1.0.0"
entrypoint = "example-document-on-letterhead.typ"
authors = ["One Fact Street Team <mailto:hello@onefact.org>"]
license = "Apache-2.0"
description = "A template for letters and experience reports for the foundation"
categories = ["Academic", "Letter", "Report"]
repository = "https://github.com/onefact/letterhead-template"

[template]
path = "template"
entrypoint = "example-document-on-letterhead.typ"
thumbnail = "example-document-on-letterhead.webp"